### ISSUE TITLE
Add deletion confirmation options

### ISSUE THREAD

**Issue by cgite** [jdgregson/o365utils#1]
https://github.com/jdgregson/Delete-Emails-O365/blob/8d434d6b4f3366bc8ba8337913b0cdbf66e4b847/Delete-Emails.ps1#L211

Perhaps add something like ` $answer = Read-Host "[Y] Yes  [N] No  [M] More details  (default is `"N`")"` after?

**Comment by jdgregson** [comment]
Good catch, I must've overlooked that. This has been added in commit 1011523. Thanks!
